name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/bubsy21/Adv360-Pro-ZMK"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "bubsy21"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_PROJECT_ID: "<60887536>"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
