name: Mirror to GitLab

on:
  push:
    branches:
      - miryoku  # Adjust this to your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/username/repo.git
          git push gitlab main  # Adjust this to your default branch
